name: ITFACT-CJF

services:
  postgresql:
    image: postgres:17.6
    container_name: CJF-POSTGRESQL
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: CJF
      POSTGRES_USER: cjf
      POSTGRES_PASSWORD: cjf
    volumes:
      - CJF_POSTGRES_DATA:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cjf -d CJF"]
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      org.opencontainers.image.title: "CJF - POSTGRESQL"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: cjf-fastapi:latest
    container_name: CJF-FASTAPI
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg://cjf:cjf@postgresql:5432/CJF
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8000:8000"
    labels:
      org.opencontainers.image.title: "CJF - FASTAPI"

  nginx:
    image: nginx:alpine
    container_name: CJF-NGINX
    restart: unless-stopped
    depends_on:
      fastapi:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      org.opencontainers.image.title: "CJF - NGINX"

  redis:
    image: redis:7-alpine
    container_name: CJF-REDIS
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - CJF_REDIS_DATA:/data
    labels:
      org.opencontainers.image.title: "CJF - REDIS"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: CJF-RABBITMQ
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: cjf
      RABBITMQ_DEFAULT_PASS: cjf
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - CJF_RABBITMQ_DATA:/var/lib/rabbitmq
    labels:
      org.opencontainers.image.title: "CJF - RABBITMQ"

volumes:
  CJF_POSTGRES_DATA:
  CJF_REDIS_DATA:
  CJF_RABBITMQ_DATA: